auto_login:
  auto_login_enabled:
    default: false
    client: true
  auto_login_strategy:
    default: "redirect"
    type: enum
    choices:
      - redirect
      - iframe
    client: true
  auto_login_days_cooldown_after_logout:
    default: true
    client: true
    default: 30
    min: 1
    max: 365